platform :ios, "9.0"

use_frameworks!

def rx_pods
    pod 'RxSwift', '~> 3.0.0-beta.2'
    pod 'RxCocoa', '~> 3.0.0-beta.2'
end

def rx_test_pods
    pod 'RxTests'
end

def rx_data_pods
    pod 'RxDataSources', '~> 1.0.0-beta.3'
end

def net_pods
    pod 'Alamofire', '~> 4.0.0'
    pod 'RxAlamofire', '~> 3.0.0-beta.1'
    pod 'Moya', '~> 8.0.0-beta.2'
    pod 'Moya/RxSwift', '~> 8.0.0-beta.2'
end

def model_pods
    pod 'ObjectMapper'
end

target 'RxWhy' do
    rx_pods
end

target 'RxTableView' do
    rx_pods
    rx_data_pods
end

target 'RxNetwork' do
    rx_pods
    rx_data_pods
    net_pods
    model_pods
end

target 'RxScheduler' do
    rx_pods
end

target 'RxExtensions' do
    rx_pods
    rx_data_pods
    net_pods
    pod 'RxOptional'
    # pod 'ObservableArray-RxSwift'
    pod 'NSObject+Rx'
end

target 'MVVM' do
    rx_pods
    pod 'NSObject+Rx'
    pod 'RxOptional'
    pod 'Proposer'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
